Repository skdGT/feup-cgra, pull requests merged in 2020-05, with the labels that each got.

#63 AutoPilot Fix
  proj/MyVehicle.js
Labels: bug-fix

#64 Blimp to Move in Altitude
  proj/MyBlimpBody.js
  proj/MyScene.js
  proj/MySupply.js
  proj/MyVehicle.js
Labels: enhancement, extra

#69 AutoPilot - Deactivation | Suppy - Updated Textures
  proj/MyScene.js
  proj/MySupply.js
  proj/MyVehicle.js
  proj/images/supply/crate.jpg
  proj/images/supply/crate1.png
  proj/images/supply/crate2.png
  proj/images/supply/crate3.png
  proj/images/supply/crate4.png
  proj/images/supply/crate5.png
  proj/images/supply/package.jpg
Labels: bug-fix, enhancement

#70 WireFrame
  proj/MyBillboard.js
  proj/MyBlimpBody.js
  proj/MyGondola.js
  proj/MyInterface.js
  proj/MyPropeller.js
  proj/MyQuad.js
  proj/MyRudder.js
  proj/MyScene.js
  proj/MySupply.js
  proj/MyTerrain.js
  proj/MyTriangle.js
  proj/MyUnitCubeQuad.js
  proj/MyVehicle.js
  proj/main.js
  submissao/ident-t3g01-n.txt
Labels: enhancement

#71 Updated Progress Bar Shader
  proj/MyBillboard.js
  proj/shaders/progress_bar.frag
  proj/shaders/progress_bar.vert
Labels: bug-fix, enhancement
