Repository skdGT/feup-cgra, pull requests merged in 2020-04, with the labels that each got.

#8 Project - AutoPilot
  proj/MyBlimpBody.js
  proj/MyGondola.js
  proj/MyScene.js
  proj/MySphere.js
  proj/MyVehicle.js
  proj/main.js
Labels: enhancement

#7 proj-B | Vehicle Model
  proj/MyBlimpBody.js
  proj/MyGondola.js
  proj/MyScene.js
  proj/MySphere.js
  proj/MyVehicle.js
  proj/main.js
Labels: enhancement

#12 Animação dos Lemes Verticais
  proj/MyBlimpBody.js
  proj/MyVehicle.js
Labels: enhancement

#11 Propeller
  proj/MyBlimpBody.js
  proj/MyPropeller.js
  proj/MyScene.js
  proj/MyTriangle.js
  proj/MyVehicle.js
  proj/main.js
Labels: enhancement

#18 proj-B-3.1 | Texturas Blimp
  proj/MyBlimpBody.js
  proj/MyRudder.js
  proj/MyScene.js
  proj/MyTriangle.js
  proj/MyVehicle.js
  proj/images/goodyear.jpg
  proj/images/goodyear_blue.jpg
  proj/images/goodyear_yellow.jpg
Labels: enhancement

#21 Fixed Lap time on AutoPilot
  proj/MyScene.js
  proj/MyVehicle.js
Labels: bug-fix

#25 Terreno - Shader
  proj/MyScene.js
  proj/MyVehicle.js
  proj/main.js
  proj/shaders/terrain.frag
  proj/shaders/terrain.vert
Labels: enhancement

#27 Melhoria de Desempenho
  proj/MyVehicle.js
Labels: bug-fix, enhancement

#34 Posição da câmara e Alinhamento do Terrenho
  proj/MyScene.js
Labels: enhancement

#39 Iluminação Cubemap
  proj/MyCubeMap.js
Labels: enhancement

#40 MySupplyBase Base Code
  proj/MyQuad.js
  proj/MyScene.js
  proj/MySupply.js
  proj/MyUnitCubeQuad.js
  proj/main.js
Labels: enhancement

#42 Supply - Modelação
  proj/MySupply.js
  proj/MyUnitCubeQuad.js
  proj/images/supply/crate1.png
  proj/images/supply/crate2.png
  proj/images/supply/crate3.png
  proj/images/supply/crate4.png
  proj/images/supply/crate5.png
Labels: enhancement

#41 Organizando
  proj/MyScene.js
  proj/MySupply.js
Labels: enhancement

#51 MyTerrain - Now as a single Class
  proj/MyScene.js
  proj/MyTerrain.js
  proj/main.js
Labels: bug-fix, enhancement, refactoring

#52 Flag
  proj/MyBlimpBody.js
  proj/MyScene.js
  proj/MyUnitCubeQuad.js
  proj/MyVehicle.js
  proj/shaders/flag.frag
  proj/shaders/flag.vert
Labels: enhancement

#57 6.1 Texture and Ropes
  proj/MyBlimpBody.js
  proj/MyInterface.js
  proj/MyScene.js
  proj/images/goodyear_flag.png
  proj/images/portugal_flag.png
Labels: enhancement
